name: Responsiveness-Check-Screenshots

on: [pull_request]

jobs:
  screenshots:
    runs-on: ubuntu-latest
    env:
      blank-line: "\n\n"
      site-name: klox-dup # replace with your netlify site name
    steps:
    - name: Wait for Netlify Preview Deploy Pages Check to change to neutral (complete)
      uses: fountainhead/action-wait-for-check@v1.0.0
      id: wait-for-page-check
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ github.event.pull_request.head.sha || github.sha }}
        checkName: Pages changed - ${{ env.site-name }}
    - name: Wait for Preview URL to return status 200
      if: steps.wait-for-page-check.outputs.conclusion == 'neutral'
      uses: jakepartusch/wait-for-netlify-action@v1.3
      id: wait-for-200
      with:
        site_name: ${{ env.site-name }}
    - uses: actions/checkout@v2
    - name: Install puppeteer-headful
      uses: mujo-code/puppeteer-headful@master
      env:
        CI: 'true'
    - name: Get Screenshots
      uses: flameddd/screenshots-ci-action@v1.1.1
      with:
        url: ${{ steps.wait-for-200.outputs.url }}
        # noDesktop: true # false by default
        fullPage: true # false by default
        devices: "iPhone 6,iPad Pro" # add / remove more devices as listed here: https://github.com/marketplace/actions/screenshots-ci-action#full-mobile-devices-options-httpsgithubcompuppeteerpuppeteerblobmasterexperimentalpuppeteer-firefoxlibdevicedescriptorsjs
    - name: Upload Screenshots to Imgur
      id: upload
      uses: devicons/public-upload-to-imgur@v2.2.1
      with:
        path: ./screenshots/
        client_id: ${{secrets.IMGUR_CLIENT_ID}} # create a client id on imgur and set it as your repository secret
    - name: Make Comment with Screenshots
      uses: thollander/actions-comment-pull-request@v1        
      with:
        message: ${{ format('<details><summary>Check for Responsiveness - View the Preview Deployment at different viewport sizes</summary> {0}{1} </details>', env.blank-line, join(fromJSON(steps.upload.outputs.markdown_urls), ' ')) }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}